# Generated by Django 4.1.3 on 2023-02-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('custom_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('field', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('user', models.PositiveIntegerField()),
                ('device', models.PositiveIntegerField()),
            ],
        ),
    ]
